application: oakhill-dl
version: 1-01
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /i
  static_dir: i
- url: /js
  static_dir: js

- url: /admin/.*
  script: greek_admin.application
  login: admin
- url: /.*
  script: main.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest